"""Thông số cố định mặc định của mạng không dây."""

DEFAULT_AREA_WIDTH_M = 1000.0
DEFAULT_AREA_HEIGHT_M = 1000.0
DEFAULT_MIN_ALTITUDE_M = 50.0
DEFAULT_MAX_ALTITUDE_M = 300.0
DEFAULT_COVERAGE_THRESHOLD_DBM = -90.0
